### ISSUE TITLE
"Reset All" button does not work 

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsmApp#100]
On the homepage side-panel, the **reset all** button does not reset the side-panel inputs.

![image](https://github.com/Gilead-BioStats/gsmApp/assets/40671730/8264178f-6290-491a-a2c1-74d252b26604)

**Comment by taylorrodgers** [comment]
@jwildfire, I can make this change real quick, but should we use this ticket as an opportunity to **hide** the **Site** filter and the **Participant** filter unless the are on a panel that uses that filter?

For example, the **Overview** tab does not use **Site** or **Participant** for anything. I believe the **Metric Details** tab only uses **Site**. The **Participants Details** tab (I think) only uses **Participant**, but I'd have to double check.

My thinking is we could reveal those filters when it's relevant. Thoughts?
