### ISSUE TITLE
Improve interactivity for tables

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsmApp#113]
- Turn off row-highlighting for tables
- Any click on a subject id should jump to the subject-level table
- Any click on a site id should jump to the metric module

**Comment by taylorrodgers** [comment]
### What Cannot Be Done Yet
This ticket will involve modifying `gsm::Overview_Table` to have desired interactivity on that particular table. An alternative is to re-create the table within this package so we can modify it ourselves, which I'm open to doing. This will also enable us to add hypertext to the Site ID on that table.

### Other Notes
Clicking on a subject ID does indeed take you to the participants detail table. I have not been able to create that issue.

All other tables have their row-highlighting turned off now.

**Comment by taylorrodgers** [comment]
**Follow-up notes on site id select:**

- We will need an `observeEvent` function to listen for when the site filter is updated. When it is update, we will update the tab selection
- `Overview_Table()` may need modification in `gsm` or to be duplicated and modified within `gsmApp`, because it does not have an actionlink for site id
- Time series plot does not update filter as the other widgets do

**Comment by taylorrodgers** [comment]
The following appear to be sourced in `gsm` or involve areas of JavaScript that I'm unclear how to resolve:

- `overviewTable()`, which will require either duplicating and modifying or creating a separate ticket for `gsm`
- `renderWidget_TimeSeries()`, which could be a `gsmApp` package issue or a `gsm` package issue. I'm unclear.

**Comment by taylorrodgers** [comment]
@samussiah, this is part of the PR that I sent to you for review. Jeremy (and once upon a time, Matt) had suggested I complete what I could on this ticket. I'm personally fine with leaving the ticket opened or creating a new one once the GSM package update are complete. Thanks!

**Comment by taylorrodgers** [comment]
The app was updated as much as it could be without updates from `gsm`. Closing now. A similar ticket may need to be re-opened after gsm re-factors are completed.
