### ISSUE TITLE
qs deserialization bug fix

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsmApp#125]
The qs package has a [bug fix for the deserialization promises bug](https://github.com/traversc/qs/issues/93) (like in R's RDS). Unfortunately the fix that's on CRAN now breaks old qs files.

I'm not sure that discussion is going to be the final fix, but we should watch it and deal with it.

- [ ] Short term: Use `qs::set_trust_promises(TRUE)` in the demo app, with the dev version of {qs}. This tells qs to go ahead and load the old things.
- [ ] Long term: Actually fix things in the app. May be as simple as resaving the qs files, but may require other protections, particularly if users might have qs files saved in the older format.

**Comment by jwildfire** [comment]
Yeah, we shouldn't need `{qs}` when we do the v2 re-write, so let's only spend minimal time on this for now.

**Comment by jonthegeek** [comment]
Fixed enough.
