### ISSUE TITLE
Create more consistency in function / file names

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsmApp#152]
Let's be consistent about naming. `study_overview_server()` and `modScatterServer()` are using different naming schemes. Their filenames follow the same pattern, but not the function names. Most functions appear to follow the (somewhat more standard for R) snake_case format, so let's standardize around that (without the `mod_` piece, too, since the others don't use it). So this should be `scatter_server`, and should be updated in its definition in `mod_scatter_server.R` as well.

**Comment by taylorrodgers** [comment]
@jonthegeek, I am debating making adding `mod_` to the function names as well (in addition to the file names) to make it easier to distinguish in line. What do you think?

**Comment by jonthegeek** [comment]
I think I prefer it but didn't want to force that much change. If you're thinking the same, let's do it!
