### ISSUE TITLE
Feature: Modify run_app function to pull in sample data only if paremeter set to true.

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsmApp#153]
## Feature Details
The current `run_app` function pulls in sample data if the inputs are null. (See code further below).

We'd like to separate this into `run_app` and `run_sample_app`.

`run_app` would not allow null values and would not pull in sample data.

`run_sample_app` would use sample data with no parameters or arguments passed to the function.

## Original Code Below

```
run_app <- function(
    dfResults = NULL,
    dfGroups = NULL,
    dfMetrics = NULL,
    dfBounds = NULL) {
  dfResults <- dfResults %||% gsm::reportingResults %>%
    dplyr::filter(.data$SnapshotDate == max(.data$SnapshotDate))
  dfGroups <- dfGroups %||% gsm::reportingGroups
  dfMetrics <- dfMetrics %||% gsm::reportingMetrics
  dfBounds <- dfBounds %||% gsm::reportingBounds %>%
    dplyr::filter(.data$SnapshotDate == max(.data$SnapshotDate))

  shinyApp(
    ui = ui(),
    server = function(input, output, session) {
      gsmApp::server(input, output, session,
        dfResults = dfResults,
        dfGroups = dfGroups,
        dfMetrics = dfMetrics,
        dfBounds = dfBounds
      )
    }
  )
}

```

**Comment by jonthegeek** [comment]
What do you think about a wrapper that adds the sample data and then calls run_app? That way the normal use case isn't polluted with functionality that won't be used outside of demos/testing. At first I was thinking the wrapper shouldn't be exported, but it wouldn't hurt to have it available for users to learn the package.

**Comment by samussiah** [comment]
Wrapper sound ideal.

**Comment by jonthegeek** [comment]
Maybe `run_sample_app()`?

**Comment by taylorrodgers** [comment]
@jonthegeek, @samussiah, what do you think of the updated description above? Does that capture the intent?

I think `run_sample_app()` would work for my purposes.

**Comment by jonthegeek** [comment]
@taylorrodgers Yup, that's what I'm thinking... with a couple potential tweaks:

- `run_sample_app()` pretty definitely shouldn't have any arguments (until/unless we have multiple options for samples).
- We need to check the underlying functions to see if any of these are optional. I think one or two things might be optional, in which case we SHOULD accept `NULL` values.

**Comment by taylorrodgers** [comment]
@jonthegeek, on the second point, are you talking about all the other functions that are not `run_app`?

**Comment by jonthegeek** [comment]
@taylorrodgers Yeah. Basically... if we don't NEED a given data.frame (eg, if it's optional for the underlying widgets), we might allow it to be `NULL`. If that isn't obvious yet... I think let's err on the side of requiring the argument, and we can switch it to a `NULL` default later if it turns out to be optional (ie, maybe we can figure out default `dfMetrics` if it's `NULL`, but for now we don't, so let's require it).

**Comment by taylorrodgers** [comment]
Hmm, I wonder if that should be a separate ticket. Honestly, I think every argument is likely to be required. I think many of the optional nulls were done based on past precedent..

**Comment by jonthegeek** [comment]
Ok, let's assume required until/unless we find that something can be optional!
