### ISSUE TITLE
QC: Github actions to deploy app to shinyapps.io

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsmApp#82]
Once we make the package public, let's create 2 pipelines that deploys the app using {clindata} whenever there is a:
- release
- PR merged to dev

Talk with Devin about internal deployment - wait until open-source for shinyapps.io deployment.

**Comment by jonthegeek** [comment]
@jwildfire Do we have a gilead-biostats (or similar) shinyapps.io account? Free tier should be fine for what we want (although the sample data MIGHT end up pushing things a bit; they don't technically have a size limit that I can see, but I suspect there's SOME sort of limit).
