### ISSUE TITLE
Clicking a row in Site Participant table should update Participant selector

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsmApp#97]
e.g. Row for Participant 1147 was clicked and should be selected in dropdown in left hand sidebar. 
![image](https://github.com/Gilead-BioStats/gsmApp/assets/3680095/9341bf59-7e42-4136-8c26-1116173f7581)

**Comment by taylorrodgers** [comment]
I had some issues with GDASH note render JS functions. However, that issue appears to be limited to GDASH and does not appear on Atorus' workbench.

Here is video showing that the function works as intended when not on GDASH:

https://github.com/Gilead-BioStats/gsmApp/assets/76186904/a8b94821-cd51-4841-a53e-ea34ef326a16
