### ISSUE TITLE
Options in participant dropdown should be subset when a site is selected

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsmApp#98]
When a site is selected, only participants from that site should be selectable in the partcipant dropdown

**Comment by taylorrodgers** [comment]
This will be on the pull request [here](https://github.com/Gilead-BioStats/gsmApp/pull/105).

Here is video confirmation:

https://github.com/Gilead-BioStats/gsmApp/assets/76186904/e6b98487-271a-4456-9bed-fe8f382de9d9
